### ISSUE TITLE
Full screen button not working in molecules

### ISSUE THREAD

**Issue by farkon00** [kolumb/kolumb.github.io#1]
In https://kolumb.tk/en/chemistry/molecules/ full screen button isn't working. And it would be nice if you updated repo, so it will match kolumb.tk.

**Comment by kolumb** [comment]
Thanks for pointing it out! I uploaded content from kolumb.tk and now full screen button is working! Looks like it was fixed there at some point.
Also https://kolumb.github.io/ no longer redirects to kolumb.tk. But it might still redirect for you because of cached http document that has redirection. I don't know how to clear this kind of cache, because it redirects immediately :D But I tested in incognito mode.

**Comment by kolumb** [comment]
Oh, ups, I was checking not specifically English. Now it's definitely fixed!
